### ISSUE TITLE
End-of-central-directory signature not found

### ISSUE THREAD

**Issue by dausruddin** [Joentje/nordvpn-proxy#67]
I got this error repeatedly:
```
2021-06-04 22:02:11 INFO: Download and extract ovpn files
nordvpn_1  | [/app/ovpn/config/ovpn.zip]
nordvpn_1  |   End-of-central-directory signature not found.  Either this file is not
nordvpn_1  |   a zipfile, or it constitutes one disk of a multi-part archive.  In the
nordvpn_1  |   latter case the central directory and zipfile comment will be found on
nordvpn_1  |   the last disk(s) of this archive.
nordvpn_1  | unzip:  cannot find zipfile directory in one of /app/ovpn/config/ovpn.zip or
nordvpn_1  |         /app/ovpn/config/ovpn.zip.zip, and cannot find /app/ovpn/config/ovpn.zip.ZIP, period.
```

My `docker-compose.yml` is:
```
version: '3'
services:
  nordvpn:
    image: jeroenslot/nordvpn-proxy:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 103.86.96.100
      - 103.86.99.100
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ovpn-data:/app/ovpn/config
    environment:
      - USERNAME=<removed>
      - PASSWORD=<removed>
      - LOCAL_NETWORK=192.168.1.0/24
    networks:
      - default
    ports:
      - 8118:8118
    restart: always

volumes:
  ovpn-data:
```
