### ISSUE TITLE
Running 6 instances 

### ISSUE THREAD

**Issue by mrahmadt** [Joentje/nordvpn-proxy#80]
Hello

What do you think is the best way to run 6 instances (containers) with different VPN servers?

I want to run multiple applications with random ips

Thanks

**Comment by BobWs** [comment]
NordVPN allows only 5 simultaneous OpenVPN clients. If you want to run 6 containers at the same time they will be classified as simultaneous clients so IMHO it will not work. But if you want to be sure give it a try!

**Comment by mrahmadt** [comment]
Thanks BobWs

what about 5 simultaneous connection, how is it possible to do it making sure it will connect to different VPN servers?

**Comment by BobWs** [comment]
> Thanks BobWs
> 
> what about 5 simultaneous connection, how is it possible to do it making sure it will connect to different VPN servers?

I guess you could try it! Make sure to give all your containers a unique name and port number (the host port). Then configure the VPN’S you want to connect to.

**Comment by kraftzwerg** [comment]
I use 5 different docker-compose files
I only change the container name, the country, and the Port.

To connect my browsers i use port 8118, 8119, 8120, 8121, 8122

To connect other containers i use  **network_mode: "container:nordvpn-de_nordvpn-de_1"** in there docker-compose files.

If one of this subcontainers needs to be exposed over a specific port, enter that port in the nordvpn yaml, not in the container you want to expose. eg: if you want to ascess tvheadend over a proxy, but want to use tvheanend in you local network, expose the tvheadend port in the nordvpn yaml file-

```
version: "3"
services:
  nordvpn-de:
    image: jeroenslot/nordvpn-proxy:latest
    cap_add:
      - NET_ADMIN
    environment:
      - USERNAME=USERNAME
      - PASSWORD=PASSWORD
      - LOCAL_NETWORK=x.x.x.0/24
      - COUNTRY=DE
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .ovpn-data:/app/ovpn/config
    ports:
      - 8118:8118
    restart: always
```
