### ISSUE TITLE
Container doesn't establish vpn connection

### ISSUE THREAD

**Issue by ph1signals** [Joentje/nordvpn-proxy#82]
Hello Guys,

I'm building a VPS server with a plex container where  i'm trying to set a nordvpn connection
I use this image to bypass the port forwarding feature (not used by nordvpn).
After many atemps I still get the same IP adress on my plex container.  Tested with this command curl ifconfig.me

The Nordvpn-proxy container was created with the following instructions : 

```
docker run -d \
--cap-add=NET_ADMIN \
--name=vpn \
--dns=103.86.96.100 \
--dns=103.86.99.100 \
--restart=always \
-e "USERNAME=<myemail@email.com>" \
-e "PASSWORD=<mypassword>" \
-e "LOCAL_NETWORK=172.17.0.1/16" \   #IP retrieved from  docker0  network settings
-v /etc/localtime:/etc/localtime:ro \
-v ovpn-data:/app/ovpn/config \
-p 32400:32400 \     #plex port
jeroenslot/nordvpn-proxy:latest 
```

Then, the plex one : 

```
version: '3.3'
services:
    plex:
        network_mode: 'container:vpn'
        container_name: plexvpn
        environment:
            - TZ=Europe/Paris
            - PLEX_CLAIM=my_claim_code
            - 'ADVERTISE_IP=http://192.168.205.4:32400/'
        volumes:
            - '/plex/database:/config'
            - '/plex/transcode:/transcode'
            - '/plex/media:/data'
        image: linuxserver/plex
```

The NordVPn-proxy process :
d24c9f737163 jeroenslot/nordvpn-proxy:latest "runsvdir /app" 14 hours ago Up 14 hours (unhealthy) 8118/tcp, 0.0.0.0:32400->32400/tcp, :::32400->32400/tcp vpn

In fact I don't know if the vpn container is really connected to nordvpn servers and I don't how to see it

Can someone help me with this problem please ?
